version: '3.8'

services:
  db:
    container_name: bank_mysql_db
    env_file:
      - ./.env.docker
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    cap_add:
      - SYS_NICE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
