version: '3.8'

services:
  db:
    container_name: bank_mysql_db
    image: mysql
    restart: always
    env_file: ./docker.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
