export * from './user.interface';
export * from './branch.interface';
export * from './department.interfaces';
export * from './business.interfaces';
export * from './customer.interfaces';
export * from './product.interfaces';
export * from './individuals.interfaces';
export * from './officer.interfaces';
export * from './employee.interfaces';
